---
# handlers file for ansible-nexus

- name: 'start nexus'
  service: name=nexus state=started
  tags:
    - init

- name: 'restart nexus'
  service: name=nexus state=restarted

- name: 'reload nginx'
  service: name=nginx state=reloaded
