directories:
  - /docker-registry
  - /docker-registry/data
  - /docker-registry/nginx
  - /usr/local/share/ca-certificates/docker-dev-cert

node_directories:
  - /usr/local/share/ca-certificates/docker-dev-cert
  #- /root/.docker

node_files: [
  {
      src: "devdockerCA.crt",
      dest: "/usr/local/share/ca-certificates/docker-dev-cert/devdockerCA.crt",
      mode: "0644"
  }
 # {
 #     src: "registry_auth_config.json",
 #     dest: "/root/.docker/config.json",
 #     mode: "0644"
 # }

]

registry_server_files: [
  {
    src: "docker-compose.yml",
    dest: "/docker-registry/docker-compose.yml",
    mode: "0755"
  },
  {
    src: "docker-registry.conf",
    dest: "/etc/init/docker-registry.conf",
    mode: "0644"
  },
  {
    src: "registry.conf",
    dest: "/docker-registry/nginx/registry.conf",
    mode: "0644"
  },
  {
    src: "registry.password",
    dest: "/docker-registry/nginx/registry.password",
    mode: "0644"
  },
  {
    src: "devdockerCA.crt",
    dest: "/docker-registry/nginx/devdockerCA.crt",
    mode: "0644"
  },
  {
    src: "devdockerCA.crt",
    dest: "/usr/local/share/ca-certificates/docker-dev-cert/devdockerCA.crt",
    mode: "0644"
  },
  {
    src: "devdockerCA.key",
    dest: "/docker-registry/nginx/devdockerCA.key",
    mode: "0644"
  },
  {
    src: "domain.key",
    dest: "/docker-registry/nginx/domain.key",
    mode: "0644"
  },
  {
    src: "dev-docker-registry.com.csr",
    dest: "/docker-registry/nginx/dev-docker-registry.com.csr",
    mode: "0644"
  },
  {
    src: "devdockerCA.srl",
    dest: "/docker-registry/nginx/devdockerCA.srl",
    mode: "0644"
  },
  {
    src: "domain.crt",
    dest: "/docker-registry/nginx/domain.crt",
    mode: "0644"
  },
  {
    src: "docker.cfg",
    dest: "/etc/default/docker",
    mode: "0644"
  }
]
nginx_templates: [
  {
    src: "nginx-include.conf.ctmpl.j2",
    ctmplDest: "/data/nginx/templates/{{ alias }}{{ container_name }}-include.conf.ctmpl",
    dest: "/data/nginx/includes/{{ nginx_conf_name }}/{{ container_name }}.conf"
  }, {
    src: "nginx-upstream.conf.ctmpl.j2",
    ctmplDest: "/data/nginx/templates/{{ alias }}{{ container_name }}-upstream.conf.ctmpl",
    dest: "/data/nginx/upstreams/{{ alias }}{{ container_name }}.conf"
  }
]
