- name: Directories are present
  file:
    dest: "{{ item }}"
    state: directory
  with_items: master_directories
  when: swarm_master is defined
  tags: [swarm]

- name: Scripts are present
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  with_items: master_scripts
  when: swarm_master is defined
  tags: [swarm]

- name: Obsolete Docker init.d service is removed
  file:
    dest: /etc/init.d/docker
    state: absent
  tags: [swarm]

- name: Configuration is present
  copy:
    src: docker.cfg
    dest: /etc/default/docker
  register: config_result
  when: not swarm_master is defined
  tags: [swarm]
- debug: var=config_result

- name: Docker Service is restarted
  service:
    name=docker
    state=restarted
  when: config_result|changed
  tags: [swarm]

- name: Swarm node is running
  docker:
    name: swarm-node
    image: swarm
    command: join --addr={{ ip }}:2375 consul://{{ ip }}:8500/swarm
    restart_policy: always
  when: not swarm_master is defined
  tags: [swarm]

- name: Swarm master is running
  docker:
    name: swarm-master
    image: swarm
    ports: 2375:2375
    command: manage consul://{{ ip }}:8500/swarm
    restart_policy: always
    env:
      SERVICE_ID: swarm-master
  when: swarm_master is defined
  tags: [swarm]

#- name: Compose is present
#  shell: >
#    curl -L \
#    https://github.com/docker/compose/releases/download/1.2.0/docker-compose-`uname -s`-`uname -m` \
#    > /usr/local/bin/docker-compose
#  args:
#    creates: /usr/local/bin/docker-compose
#  when: swarm_master is defined
#  tags: [swarm]
#
#- name: Setting permissions
#  file:
#    path: /usr/local/bin/docker-compose
#    group: root
#    owner: root
#    mode: 0755
#  when: swarm_master is defined
#  tags: [swarm]
