- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://get.docker.com/ubuntu docker main
    update_cache: yes
    state: present
  tags: [docker]

- name: Docker is present
  apt:
    name: lxc-docker
    state: present
    force: yes
  tags: [docker]

- name: Python-pip is present
  apt:
    name: python-pip
    state: present
  tags: [docker]

- name: Docker-py is present
  #pip: name=docker-py version=0.4.0 state=present
  #pip: name=docker-py version=1.2.3 state=present
  pip: name=docker-py version=1.7.0 state=present
  tags: [docker]
