ports:
  - '80:80'

directories:
  - /data/nginx/conf.d
  - /data/nginx/includes
  - /data/nginx/logs
  - /data/nginx/upstreams
  - /data/nginx/templates
  - /data/nginx/servers

volumes:
  - /data/nginx/conf.d:/etc/nginx/conf.d
  - /data/nginx/includes:/etc/nginx/includes
  - /data/nginx/upstreams:/etc/nginx/upstreams
  - /data/nginx/servers:/etc/nginx/servers
  - /data/nginx/logs:/var/log/nginx

templates: [
  {src: 'services.conf.j2', dest: '/data/nginx/conf.d/services.conf'}
]

download_folder: /opt
ver: "3.0.0-m7"
url: "https://download.sonatype.com/nexus/3/nexus-{{ver}}-unix.tar.gz"
archive: "{{download_folder}}/nexus-{{ver}}.tar.gz"
nexus_name: "{{download_folder}}/nexus"
